### ISSUE TITLE
Discuss dashboard requirements with OEP Team.

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Site#3] opened 2021-02-23 12:30 UTC
From: Harvey, Jake <Jake.Harvey@defra.gov.uk> 
Sent: 12 February 2021 16:02
To: Edwardes, Alistair <Alistair.Edwardes@defra.gov.uk>
Cc: Connors, Emily <Emily.Connors@defra.gov.uk>; Farr, James <james.farr@defra.gov.uk>; Scheuermann, Elias <Elias.Scheuermann@defra.gov.uk>; Pathak, Maniv <Maniv.Pathak@defra.gov.uk>; McGreevy, Jessica <Jessica.McGreevy@defra.gov.uk>
Subject: OIF dashboard and the OEP

Hi Alistair,

I hope you’re well. 

I wanted to get in touch as I’ve recently joined the Interim Environmental Governance Secretariat to help prepare for the start of the Office for Environmental Protection. Maniv (CC’d) leads my team and broadly we’re working to ensure that the OEP has what it needs to carry out its report on progress against government’s goals, by laying the groundwork ahead of it picking up its statutory functions once the Environment Bill gets royal assent.

Currently we’re trying to develop our understanding of the approaches being used to report on the 25 YEP goals. We’ve spoken to Mark Jacob about the OIF, and also Rob Reid’s team about the reporting process from their side. 

I joined a presentation late last year about the OIF pipeline and dashboard, and I think some members of my team might have joined some of the sessions you ran too, but with the above in mind I wanted to get in touch and find out a little bit more about this. 

Is there any information you can share on this please? I have a few questions on how the dashboard will be used and what it will deliver, as well as whether there is any work being done to assess interactions across goals. Please do let me know if it would be best to arrange a discussion to find out more about the work you’re doing. 

Kind regards,

Jake 

Jake Harvey | IEGS Science and Analysis Team | Environmental Governance | Department for Environment, Food and Rural Affairs 
02078955109 |  jake.harvey@defra.gov.uk | Address: Ground Floor, 2 Marsham Street, London, SW1P 4DF

I am a mental health first aider, I am happy to listen.  View Your Wellbeing pages for guidance and advice on staying safe and well and find a list of MHFA here

**Comment by EFT-Defra** [comment] 2021-03-02 10:52
Duplicate of Defra-Data-Science-Centre-of-Excellence/OIF-Project-Management#116

**Closed by EFT-Defra** 2021-03-02 10:52 UTC
Labels: EPIC: Gather user requirements, Should
